export const DEFUALT_NLP_MODEL = {
  provider: {
    type: "feedyou",
    threshold: 0,
  },
  entities: [
    {
      options: [
        {
          examples: [
            "PC",
            "počítač",
            "notebook",
            "noťas",
            "stolní počítač",
            "comp",
            "notebok",
          ],
          id: "PC",
        },
      ],
      id: "PC",
    },
    {
      options: [
        {
          examples: ["myš", "ovládání"],
          id: "myš",
        },
        {
          examples: ["klávesice", "keyboard", "psaní"],
          id: "klávesnice",
        },
        {
          examples: ["telefon", "mobil", "volání"],
          id: "telefon",
        },
        {
          examples: ["PC", "notebook"],
          id: "počítač",
        },
      ],
      id: "zarizeni",
    },
    {
      options: [
        {
          examples: [
            "wifi",
            "wi-fi",
            "wifina",
            "wi-fina",
            "internet",
            "net",
            "síť",
            "web",
          ],
          id: "wifi",
        },
      ],
      id: "wifi",
    },
    {
      options: [
        {
          examples: [
            "místnost",
            "místnost",
            "místností",
            "místnosti",
            "zasedačka",
            "zasedačky",
            "zasedací místnost",
            "zasedací mísnost",
            "prostor",
            "prostory",
            "sál ",
          ],
          id: "místnost ",
        },
      ],
      id: "mistnost",
    },
    {
      options: [
        {
          examples: [
            "drum life",
            "drum",
            "drumm",
            "drumlife",
            "drummlife",
            "drum live",
            "drumlive",
          ],
          id: "drum-life",
        },
        {
          examples: ["toner empty", "empty", "tonerempty"],
          id: "toner-empty",
        },
        {
          examples: ["order toner", "ordertoner", "order"],
          id: "order-toner",
        },
        {
          examples: ["replace toner", "replacetoner", "replace"],
          id: "replace-toner",
        },
        {
          examples: [
            "fuser life",
            "fusser life",
            "fuserlife",
            "fuser live",
            "fusser live",
          ],
          id: "fuser-life",
        },
        {
          examples: [
            "belt life",
            "bellt life",
            "beltlife",
            "belt live",
            "beltlive",
          ],
          id: "belt-life",
        },
      ],
      id: "tiskarna-hlasky",
    },
    {
      options: [
        {
          examples: ["pes", "psík", "hafan"],
          id: "pes",
        },
        {
          examples: ["kočka", "kočička", "micka"],
          id: "kočka",
        },
      ],
      id: "zvire",
    },
  ],
  id: "NLP general",
  intents: [
    {
      id: "nefunguje-hardware",
      name: "Nefunguje hardware",
      dialog: "Nefunguje hardware",
      utterances: [
        "Nefunguje mi {zarizeni}",
        "Rozbila se mi {zarizeni}",
        "Zlobí {zarizeni}",
        "Blbne mi {zarizeni}",
        "Oprava {zarizeni}",
        "Potřebuju opravit {zarizeni}",
        "Chci opravit {zarizeni}",
        "Nefunkční {zarizeni}",
        "Rozbitá {zarizeni}",
        "Mám nefunkční {zarizeni}",
        "Mám rozbitý {zarizeni}",
        "Mám rozbitou {zarizeni}",
        "Rozbitý {zarizeni}",
        "Seká se mi {zarizeni}",
        "Pomalá {zarizeni}",
        "Kobliha",
      ],
    },
    {
      id: "stehovani-pc",
      name: "Stěhování PC",
      utterances: [
        "Potřebuji přestěhovat {PC}",
        "Chci přestěhovat {PC}",
        "Kdo mi přestěhuje {PC}",
        "Potřebuji přestěhovat {PC}",
        "Stěhování {PC}",
        "Přestěhování {PC}",
        "Přenesení {PC}",
        "Přemístění {PC}",
        "Chci přenést {PC}",
        "Chci přemístit {PC}",
        "Na koho se obrátit když potřebuju přestěhovat {PC}",
        "Komu zavolat když potřebuju přestěhovat {PC}",
        "Kdo mi přestěhuje {PC}",
        "Koho kontaktovat pro přestěhování {PC}",
        "Chci dát {PC} do jiné místnosti",
        "Chci dát {PC} do jiné kanceláře",
        "Chci přestěhovat {PC} do jiné mísnosti",
        "Chci přestěhovat {PC} do jiné kanceláře",
        "Stěhuji se do jiné kanceláře a {PC} chci vzít s sebou",
      ],
      dialog: "Stěhování PC dialog",
    },
    {
      id: "novy-pocitac",
      name: "Nový počítač",
      utterances: [
        "chci nový {PC}",
        "potřebuji nový {PC}",
        "kdo mi dá nový {PC}?",
        "kde zařídit nový {PC}?",
        "kde získám nový  {PC}?",
        "kde vzít nový  {PC}?",
        "nový  {PC}",
      ],
      dialog: "Nový PC dialog",
    },
    {
      id: "heslo-na-wifi",
      name: "Heslo na WiFi",
      dialog: "Heslo na wifi dialog",
      utterances: [
        "jaké je heslo na {wifi}?",
        "chci heslo na {wifi}",
        "potřebuju heslo na {wifi}",
        "chci se připojit na {wifi}",
        "heslo na {wifi}",
        "chci vědět heslo na {wifi}",
        "aktuální heslo na {wifi}?",
        " {wifi} password",
        "jaká je  {wifi}",
      ],
    },
    {
      id: "rezervace-mistnosti",
      name: "Rezervace místnosti",
      dialog: "Rezervace dialog",
      utterances: [
        "chci vytvořit rezervaci {mistnost}",
        "rezervace {mistnost}",
        "jak zarezervovat {mistnost}?",
        "rezervačka {mistnost}",
        "zabookovani {mistnost}",
        "vybookovani {mistnost}",
        "zamluveni {mistnost}",
        "kde můžu vytvořit rezervaci {mistnost}",
      ],
    },
    {
      id: "vydani-cipove-karty",
      name: "Vydání čipové karty",
      dialog: "Nová karta dialog",
      utterances: [
        "chci novou kartu",
        "chci novou čipovou kartu",
        "chci kartu pro vstup",
        "kde získám kartu?",
        "kde získám čipovou kartu?",
        "kde získám vstupní kartu?",
        "kdo mi dá čipovou kartu?",
        "kde dostanu čipovou kartu?",
        "kdo mi dá čipovou kartu?",
        "získání čipové karty",
        "vystavení karty",
        "vydání čipové karty",
      ],
    },
    {
      id: "ztrata-nebo-odcizeni-cipove-karty",
      name: "Ztráta nebo odcizení čipové karty",
      dialog: "Ztráta čipové karty dialog",
      utterances: [
        "Ukradli mi čipovou kartu",
        "Ztratil jsem čipovou kartu",
        "Ztratila jsem čipovou kartu",
        "Co mám dělat při ztrátě karty?",
        "Ztracená karta",
        "Odcizená karta",
        "Nemůžu najít čipovou kartu",
        "Nevím kde mám čipovou kartu",
        "Byla mi ukradená čipová karta",
        "Odcizení čipové karty",
        "Zcizení čipové karty",
      ],
    },
    {
      id: "nefunkcni-cipova-karta",
      name: "Nefunkční čipová karta",
      dialog: "Čipová karta dialog",
      utterances: [
        "Nefunguje mi čipová karta",
        "Nefunguje mi karta",
        "Nefunkční karta",
        "Rozbitá karta",
        "Rozbitá čipová karta",
        "Karta nefunguje na terminálu",
        "Karta nefunguje",
        "Čipová karta nefunguje",
      ],
    },
    {
      id: "pripojeni-nove-tiskarny",
      name: "Připojení nové tiskárny",
      dialog: "Připojení nové tiskárny dialog",
      utterances: [
        "připojení nové tiskárny",
        "nová tiskárna",
        "chci připojit novou tiskárnu",
        "jak připojit novou tiskárnu",
        "uvedení tiskárny do provozu",
        "jak nastavit novou tiskárnu v počítači",
        "potřebuji nastavit novou tiskárnu",
      ],
    },
    {
      id: "tiskarna-zaseknuty-papir",
      name: "Tiskárna - zaseknutý papír",
      dialog: "Tiskárna zaseknutý papír dilog",
      utterances: [
        "zaseknutý papír",
        "seknutý papír",
        "zaseknutý papír v tiskárně",
        "jak vyndat zaseknutý papír z tiskárny",
        "jak dostat zaseknutý papír z tiskárny",
        "uvíznutý papír v tiskárně",
        "papír vevnitř v tiskárně",
        "zmačkaný papír vevnitř v tiskárně",
        "zasekl se mi papír v tiskárně",
        "jak dostanu papír z tiskárny",
        "jak vyndám papír z tiskárny",
      ],
    },
    {
      id: "tiskarna-dosel-toner",
      name: "Tiskárna - došel toner",
      dialog: "Tiskárna došel toner dialog",
      utterances: [
        "došel toner",
        "prázdný toner",
        "není barva v tiskárně",
        "došla barva v tiskárně",
        "tiskárna netiskne sytě",
        "barvy v tiskárně jsou slabé",
        "je potřeba vyměnit toner",
        "jak vyměnit toner",
        "jak vyměnit toner za nový",
        "tiskárna tiskne šmouhy",
      ],
    },
    {
      id: "tiskarna-text-display",
      name: "Tiskárna text display",
      utterances: [
        "tiskárna píše drum-life",
        "na tiskárně je napsáno {tiskarna-hlasky}",
        "display tiskárny ukazuje {tiskarna-hlasky}",
        "displej tiskárny ukazuje {tiskarna-hlasky}",
        "display tiskárny píše {tiskarna-hlasky}",
        "displej tiskárny ukazuje {tiskarna-hlasky}",
        "na tiskárně bliká {tiskarna-hlasky}",
        "{tiskarna-hlasky}",
        "tiskárna {tiskarna-hlasky}",
        "text na tiskárně {tiskarna-hlasky}",
        "na obrazovce tiskárny je {tiskarna-hlasky}",
        "obrazovka tiskárny ukazuje {tiskarna-hlasky}",
        "obrazovka tiskárny píše {tiskarna-hlasky}",
        "Sluníčko je žluté {tiskarna-hlasky}",
      ],
      dialog: "Zobrazení podle hlášky",
    },
    {
      id: "tiskarna-netiskne",
      name: "Tiskárna netiskne",
      dialog: "Tiskárna netiskne dialog",
      utterances: [
        "tiskárna netiskne",
        "tiskárna nereaguje",
        "tiskárna nic nedělá",
        "tiskárna nefunguje",
        "tiskárna je rozbitá",
        "dávám tisk a nic se neděje",
        "potřebuji tisknout a nejde to",
        "nejde tisknout",
      ],
    },
    {
      id: "zkusebni-intent",
      name: "Zkušební intent",
      dialog: "zkušební dialog",
      utterances: [
        "Proč má {zvire} blechy.",
        "Co má {zvíře} jíst?",
        "Slon má dlouhý chobot",
        "Má {zvire} čtyři nohy?",
      ],
    },
  ],
  defaultDialog: "nlp-faq-answer",
};
